

from ..sezimal import Sezimal, SezimalInteger, SezimalFraction
from decimal import Decimal


#
# Length, Speed, Acceleration, Area, Volume
#
PADA_TO_METER = SezimalFraction('2_211 / 231_043')
METER_TO_PADA = PADA_TO_METER.reciprocal

DIMAPADA_TO_METER = SezimalFraction('221_100 / 231_043')
METER_TO_DIMAPADA = DIMAPADA_TO_METER.reciprocal


PADA_TO_KILOMETER = SezimalFraction('2_211 / 1_541_513_000')
KILOMETER_TO_PADA = PADA_TO_KILOMETER.reciprocal

PAMAPADA_TO_KILOMETER = SezimalFraction('13_244 / 114_513')
KILOMETER_TO_PAMAPADA = PAMAPADA_TO_KILOMETER.reciprocal


PADA_TO_CENTIMETER = SezimalFraction('1_032_324 / 231_043')
CENTIMETER_TO_PADA = PADA_TO_CENTIMETER.reciprocal


PADA_TO_MILLIMETER = SezimalFraction('14_541_424 / 231_043')
MILLIMETER_TO_PADA = PADA_TO_MILLIMETER.reciprocal

DITIPADA_TO_MILLIMETER = SezimalFraction('2_423_234 / 3_444_043')
MILLIMETER_TO_DITIPADA = DITIPADA_TO_MILLIMETER.reciprocal


#
# Vega = pada × agrima⁻¹
# Vega = pada × avrita
#
VEGA_TO_METER_PER_SECOND = SezimalFraction('4_422 / 13_213')
METER_PER_SECOND_TO_VEGA = VEGA_TO_METER_PER_SECOND.reciprocal

VEGA_TO_KILOMETER_PER_HOUR = SezimalFraction('13_244 / 5_113')
KILOMETER_PER_HOUR_TO_VEGA = VEGA_TO_KILOMETER_PER_HOUR.reciprocal

PADA_PER_AGRIMA_TO_METER_PER_SECOND = VEGA_TO_METER_PER_SECOND
METER_PER_SECOND_TO_PADA_PER_AGRIMA = METER_PER_SECOND_TO_VEGA

PADA_PER_AGRIMA_TO_KILOMETER_PER_HOUR = VEGA_TO_KILOMETER_PER_HOUR
KILOMETER_PER_HOUR_TO_PADA_PER_AGRIMA = KILOMETER_PER_HOUR_TO_VEGA

#
# Tevara = pada × agrima⁻²
#
# 1 m/s² = 3.412 tvr = 3.412 pad/ang²
# 1 tvr = 1 ÷ 3.412 m/s²
#
TEVARA_TO_METER_PER_SQUARE_SECOND = SezimalFraction('44_220 / 2_521')
METER_PER_SQUARE_SECOND_TO_TEVARA = TEVARA_TO_METER_PER_SQUARE_SECOND.reciprocal

# PADA_PER_SQUARE_AGRIMA_TO_METER_PER_SQUARE_SECOND = TEVARA_TO_METER_PER_SQUARE_SECOND
# METER_PER_SQUARE_SECOND_TO_PADA_PER_SQUARE_AGRIMA = METER_PER_SQUARE_SECOND_TO_TEVARA

#
# Keshe = pada²
#
KESHE_TO_SQUARE_METER = SezimalFraction('5_332_521 / 102_235_433_213')
SQUARE_METER_TO_KESHE = KESHE_TO_SQUARE_METER.reciprocal

SQUARE_PADA_TO_SQUARE_METER = KESHE_TO_SQUARE_METER
SQUARE_METER_TO_SQUARE_PADA = SQUARE_METER_TO_KESHE

KESHE_TO_SQUARE_KILOMETER = SezimalFraction('5_332_521 / 3_451_550_303_213_000_000')
SQUARE_KILOMETER_TO_KESHE = KESHE_TO_SQUARE_KILOMETER.reciprocal

#
# Dishumakeshe = DSkex = ESpad² = 1_000_000_000_000 pad²
#
# 1 km² = 0.41 DSkex = 0.41 ESpad²
# 1 DSkex = 1 ESpad² = 1.25 km²
#
DISHUMAKESHE_TO_SQUARE_KILOMETER = SezimalFraction('1_354_105_104 / 1_044_050_213')
SQUARE_KILOMETER_TO_DISHUMAKESHE = DISHUMAKESHE_TO_SQUARE_KILOMETER.reciprocal

SQUARE_PAMAPADA_TO_SQUARE_KILOMETER = SezimalFraction('225_314_144 / 14_101_133_213')
SQUARE_KILOMETER_TO_SQUARE_PAMAPADA = SQUARE_PAMAPADA_TO_SQUARE_KILOMETER.reciprocal

#
# Aytan = pada³
#
AYTAN_TO_CUBIC_METER = SezimalFraction('21_123_532_331 / 24_115_052_350_444_043')
CUBIC_METER_TO_AYTAN = AYTAN_TO_CUBIC_METER.reciprocal

CUBIC_PADA_TO_CUBIC_METER = AYTAN_TO_CUBIC_METER
CUBIC_METER_TO_CUBIC_PADA = CUBIC_METER_TO_AYTAN

AYTAN_TO_LITER = SezimalFraction('141_144_224_351_544 / 24_115_052_350_444_043')
LITER_TO_AYTAN = AYTAN_TO_LITER.reciprocal

CUBIC_PADA_TO_LITER = AYTAN_TO_LITER
LITER_TO_CUBIC_PADA = LITER_TO_AYTAN

