

from ..sezimal import Sezimal, SezimalInteger, SezimalFraction
from decimal import Decimal


#
# Proportions
#
PERNIFF_TO_PERCENTAGE = SezimalFraction('244 / 100')
PERCENTAGE_TO_PERNIFF = SezimalFraction('100 / 244')
PERNIFF_TO_PERCENTAGE.reciprocal = PERCENTAGE_TO_PERNIFF
PERCENTAGE_TO_PERNIFF.reciprocal = PERNIFF_TO_PERCENTAGE

PERSIXNIFF_TO_PERCENTAGE = SezimalFraction('244 / 1_000')
PERCENTAGE_TO_PERSIXNIFF = SezimalFraction('1_000 / 244')
PERSIXNIFF_TO_PERCENTAGE.reciprocal = PERCENTAGE_TO_PERSIXNIFF
PERCENTAGE_TO_PERSIXNIFF.reciprocal = PERSIXNIFF_TO_PERCENTAGE

PERUNEXIAN_TO_PERCENTAGE = SezimalFraction('244 / 10_000')
PERCENTAGE_TO_PERUNEXIAN = SezimalFraction('10_000 / 244')
PERUNEXIAN_TO_PERCENTAGE.reciprocal = PERCENTAGE_TO_PERUNEXIAN
PERCENTAGE_TO_PERUNEXIAN.reciprocal = PERUNEXIAN_TO_PERCENTAGE

PERNIFF_TO_PERMILLE = SezimalFraction('4_344 / 100')
PERMILLE_TO_PERNIFF = SezimalFraction('100 / 4_344')
PERNIFF_TO_PERMILLE.reciprocal = PERMILLE_TO_PERNIFF
PERMILLE_TO_PERNIFF.reciprocal = PERNIFF_TO_PERMILLE

PERSIXNIFF_TO_PERMILLE = SezimalFraction('4_344 / 1_000')
PERMILLE_TO_PERSIXNIFF = SezimalFraction('1_000 / 4_344')
PERSIXNIFF_TO_PERMILLE.reciprocal = PERMILLE_TO_PERSIXNIFF
PERMILLE_TO_PERSIXNIFF.reciprocal = PERSIXNIFF_TO_PERMILLE

PERUNEXIAN_TO_PERMILLE = SezimalFraction('4_344 / 10_000')
PERMILLE_TO_PERUNEXIAN = SezimalFraction('10_000 / 4_344')
PERUNEXIAN_TO_PERMILLE.reciprocal = PERMILLE_TO_PERUNEXIAN
PERMILLE_TO_PERUNEXIAN.reciprocal = PERUNEXIAN_TO_PERMILLE
