#!/usr/bin/env python

import argparse
import os
import pathlib

parser = argparse.ArgumentParser(description='List directory content using sezimal numbers and dates')
parser.add_argument('directory', default=None, nargs='*', help='Directory')
parser.add_argument('-l', '--locale', dest='locale', nargs='?', default=None, help='Locale')
parser.add_argument('-dtf', '--date-time-format', dest='date_time_format', nargs='?', default=None, help='Date and time format, use it to get ISO/Gregorian date and time')
parser.add_argument('-N', '--niftimal', dest='niftimal', action=argparse.BooleanOptionalAction, help='Use niftimal values')
parser.add_argument('-D', '--decimal', dest='decimal', action=argparse.BooleanOptionalAction, help='Use decimal values')
parser.add_argument('-Z', '--dozenal', dest='dozenal', action=argparse.BooleanOptionalAction, help='Use dozenal values')
parser.add_argument('-A', '--all', dest='all', action=argparse.BooleanOptionalAction, help='List all, including hidden files/directories')
parser.add_argument('-NP', '--no-prefixes', dest='no_prefixes', action=argparse.BooleanOptionalAction, help='Numbers without prefixes')
parser.add_argument('-SD', '--sezimal-digits', dest='sezimal_digits', action=argparse.BooleanOptionalAction, help='Numbers are sezimal digits')
parser.add_argument('-SP', '--sezimal-punctuation', dest='sezimal_punctuation', action=argparse.BooleanOptionalAction, help='Separators are sezimal punctuation')
parser.add_argument('-us', '--unit_steps', dest='unit_steps', nargs='?', default=None, help='Astakas prefix steps (default 3)')


from swixknife import sezimal_locale, SezimalInteger
from swixknife.terminal import SezimalDirectoryList


if __name__ == '__main__':
    arguments = parser.parse_args()

    locale = sezimal_locale(arguments.locale)

    original_path = ''

    if len(arguments.directory) == 1:
        original_path = arguments.directory[0]
        original_path = str(pathlib.Path(original_path).absolute())

        if os.path.isdir(original_path):
            dl = os.listdir(original_path)

            for name in dl:
                arguments.directory.append(str(pathlib.Path(original_path, name).absolute()))

    sdl = SezimalDirectoryList(arguments.directory or None)
    sdl.original_path = original_path
    sdl.is_niftimal = arguments.niftimal
    sdl.is_decimal = arguments.decimal
    sdl.is_dozenal = arguments.dozenal
    sdl.show_hidden = arguments.all

    if arguments.unit_steps:
        sdl.unit_steps = int(SezimalInteger(arguments.unit_steps))

    sdl.locale = locale

    if arguments.decimal:
        sdl.date_time_format = arguments.date_time_format or '#9d/#9m/#9>y #@W %H:%M'
        # sdl.date_time_format = arguments.date_time_format or '%d/%m/%y %a %H:%M'
    elif arguments.dozenal:
        sdl.date_time_format = arguments.date_time_format or '#↋d/#↋m/#↋>y #@W #↋↋u:#↋↋p'
    elif arguments.sezimal_digits:
        if arguments.sezimal_punctuation:
            sdl.date_time_format = arguments.date_time_format or '#!d/#!m/#!>y #@W #!u󱹮#!p'
        else:
            sdl.date_time_format = arguments.date_time_format or '#!d/#!m/#!>y #@W #!u:#!p'
    else:
        if arguments.sezimal_punctuation:
            sdl.date_time_format = arguments.date_time_format or '#d/#m/#>y #@W #u󱹮#p'
        else:
            sdl.date_time_format = arguments.date_time_format or '#d/#m/#>y #@W #u:#p'

    sdl.use_prefixes = not arguments.no_prefixes
    sdl.use_sezimal_digits = arguments.sezimal_digits
    sdl.use_sezimal_punctuation = arguments.sezimal_punctuation
    sdl.terminal_list()
