
__all__ = (
    '_OPERATOR',
    '_IN_PREPARED_EXPRESSION_OPERATION',
    '_IN_EXPRESSION_OPERATION',
    '_NICE_OPERATION',
    '_PER_OPERATIONS',
    '_PER_OPERATIONS_DECIMAL_TO_SEZIMAL',
    '_PER_OPERATIONS_SEZIMAL_TO_DECIMAL',
    '_NO_SPACE_OPERATIONS',
    '_TRIGONOMETRIC_FUNCTION',
    '_CONSTANTS', 'e', 'π', 'τ', 'φ'
)

from ..constants import E, PI, TAU, GOLDEN_RATIO


_OPERATOR = {
    #
    # Operators
    #
    '+': ' __ADD__ ',
    '−': ' __SUBTRACT__ ',
    '-': ' __SUBTRACT__ ',
    '÷': ' __DIVIDE__ ',
    '/': ' __DIVIDE__ ',
    '^': ' __POWER__ ',
    '**': ' __POWER__ ',
    '×': ' __MULTIPLY__ ',
    '*': ' __MULTIPLY__ ',
    '%': ' __PERCENT__ ',
    '‰': ' __PERMILLE__ ',
    '‱': ' __PERMYRIAD__ ',
    '󱹰': ' __PERSIX__ ',
    '󱹱': ' __PERNIF__ ',
    '󱹲': ' __PERARDA__ ',
    '󱹳': ' __PERSIXARDA__ ',
    '󱹴': ' __PERNIFARDA__ ',
    '󱹵': ' __PERSHADARA__ ',
    '󱹶': ' __PERSIXSHADARA__ ',
    '󱹷': ' __PERNIFSHADARA__ ',
    '󱹸': ' __PERARDASHADARA__ ',
    '󱹹': ' __PERSIXARDASHADARA__ ',
    '󱹺': ' __PERNIFARDASHADARA__ ',
    '󱹻': ' __PERDISHADARA__ ',
    '󱹼': ' __PERTRISHADARA__ ',
    '󱹽': ' __PERCHARSHADARA__ ',
    '󱹾': ' __PERPANSHADARA__ ',
    '󱹿': ' __PERSHASHADARA__ ',
    '±': ' __PLUS_MINUS__ ',
    'mod': ' __MODULO__ ',
    '!': ' __FACTORIAL__ ',

    #
    # Functions and “punctuation”
    #
    'ln': ' __NATURAL_LOGARITHM__ ',
    'lsez': ' __SEZIMAL_LOGARITHM__ ',
    'ldec': ' __DECIMAL_LOGARITHM__ ',
    '²': ' __SQUARE__ ',
    '\u200b²': ' __SQUARE__ ',
    'sqrt': ' __SQUARE_ROOT__ ',
    '³': ' __CUBE__ ',
    '\u200b³': ' __CUBE__ ',
    'cbrt': ' __CUBIC_ROOT__ ',
    'SIN(': ' __SINE__ ',
    'arcsin(': ' __ARC_SINE__ ',
    'asin(': ' __A_SINE__ ',
    'CSC(': ' __COSECANT__ ',
    'arccsc(': ' __ARC_COSECANT__ ',
    'acsc(': ' __A_COSECANT__ ',
    'COS(': ' __COSINE__ ',
    'arccos(': ' __ARC_COSINE__ ',
    'acos(': ' __A_COSINE__ ',
    'SEC(': ' __SECANT__ ',
    'arcsec(': ' __ARC_SECANT__ ',
    'asec(': ' __A_SECANT__ ',
    'TAN(': ' __TANGENT__ ',
    'arctan(': ' __ARC_TANGENT__ ',
    'atan(': ' __A_TANGENT__ ',
    'COT(': ' __COTANGENT__ ',
    'arccot(': ' __ARC_COTANGENT__ ',
    'acot(': ' __A_COTANGENT__ ',
    'SINH(': ' __HYPERBOLIC_SINE__ ',
    'arcsinh(': ' __HYPERBOLIC_ARC_SINE__ ',
    'asinh(': ' __HYPERBOLIC_A_SINE__ ',
    'CSCH(': ' __HYPERBOLIC_COSECANT__ ',
    'arccsch(': ' __HYPERBOLIC_ARC_COSECANT__ ',
    'acsch(': ' __HYPERBOLIC_A_COSECANT__ ',
    'COSH(': ' __HYPERBOLIC_COSINE__ ',
    'arccosh(': ' __HYPERBOLIC_ARC_COSINE__ ',
    'acosh(': ' __HYPERBOLIC_A_COSINE__ ',
    'SECH(': ' __HYPERBOLIC_SECANT__ ',
    'arcsech(': ' __HYPERBOLIC_ARC_SECANT__ ',
    'asech(': ' __HYPERBOLIC_A_SECANT__ ',
    'TANH(': ' __HYPERBOLIC_TANGENT__ ',
    'arctanh(': ' __HYPERBOLIC_ARC_TANGENT__ ',
    'atanh(': ' __HYPERBOLIC_A_TANGENT__ ',
    'COTH(': ' __HYPERBOLIC_COTANGENT__ ',
    'arccoth(': ' __HYPERBOLIC_ARC_COTANGENT__ ',
    'acoth(': ' __HYPERBOLIC_A_COTANGENT__ ',
    '(': ' __LEFT_PARENTHESIS__ ',
    ')': ' __RIGHT_PARENTHESIS__ ',
}

_IN_PREPARED_EXPRESSION_OPERATION = {
    '__ADD__': '+',
    '__SUBTRACT__': '-',
    '__DIVIDE__': '/',
    '__MULTIPLY__': '*',
    '__POWER__': '**',
    '__PERCENT__': "/Sezimal('244')",
    '__PERMILLE__': "/Sezimal('4_344')",
    '__PERMYRIAD__': "/Sezimal('114_144')",
    '__PERSIX__': "/Sezimal('10')",
    '__PERNIF__': "/Sezimal('100')",
    '__PERARDA__': "/Sezimal('1_000')",
    '__PERSIXARDA__': "/Sezimal('10_000')",
    '__PERNIFARDA__': "/Sezimal('100_000')",
    '__PERSHADARA__': "/Sezimal('1_000_000')",
    '__PERSIXSHADARA__': "/Sezimal('1e11')",
    '__PERNIFSHADARA__': "/Sezimal('1e12')",
    '__PERARDASHADARA__': "/Sezimal('1e13')",
    '__PERSIXARDASHADARA__': "/Sezimal('1e14')",
    '__PERNIFARDASHADARA__': "/Sezimal('1e15')",
    '__PERDISHADARA__': "/Sezimal('1e20')",
    '__PERTRISHADARA__': "/Sezimal('1e30')",
    '__PERCHARSHADARA__': "/Sezimal('1e40')",
    '__PERPANSHADARA__': "/Sezimal('1e50')",
    '__PERSHASHADARA__': "/Sezimal('1e100')",
    '__LEFT_PARENTHESIS__': '(',
    '__RIGHT_PARENTHESIS__': ')',
    '__MODULO__': 'mod',
    '__NATURAL_LOGARITHM__': 'self.ln',
    '__SEZIMAL_LOGARITHM__': 'self.lsez',
    '__DECIMAL_LOGARITHM__': 'self.ldec',
    '__SQUARE__': "**Sezimal('2')",
    '__SQUARE_ROOT__': 'self.sqrt',
    '__CUBE__': "**Sezimal('3')",
    '__CUBIC_ROOT__': 'self.cbrt',
    '__FACTORIAL__': '.factorial()',
    '__SINE__': 'self.SIN(',
    '__ARC_SINE__': 'self.arcsin(',
    '__A_SINE__': 'self.asin(',
    '__COSECANT__': 'self.CSC(',
    '__ARC_COSECANT__': 'self.arccsc(',
    '__A_COSECANT__': 'self.acsc(',
    '__COSINE__': 'self.COS(',
    '__ARC_COSINE__': 'self.arccos(',
    '__A_COSINE__': 'self.acos(',
    '__SECANT__': 'self.SEC(',
    '__ARC_SECANT__': 'self.arcsec(',
    '__A_SECANT__': 'self.asec(',
    '__TANGENT__': 'self.TAN(',
    '__ARC_TANGENT__': 'self.arctan(',
    '__A_TANGENT__': 'self.atan(',
    '__COTANGENT__': 'self.COT(',
    '__ARC_COTANGENT__': 'self.arccot(',
    '__A_COTANGENT__': 'self.acot(',
    '__HYPERBOLIC_SINE__': 'self.SINH(',
    '__HYPERBOLIC_ARC_SINE__': 'self.arcsinh(',
    '__HYPERBOLIC_A_SINE__': 'self.asinh(',
    '__HYPERBOLIC_COSECANT__': 'self.CSCH(',
    '__HYPERBOLIC_ARC_COSECANT__': 'self.arccsch(',
    '__HYPERBOLIC_A_COSECANT__': 'self.acsch(',
    '__HYPERBOLIC_COSINE__': 'self.COSH(',
    '__HYPERBOLIC_ARC_COSINE__': 'self.arccosh(',
    '__HYPERBOLIC_A_COSINE__': 'self.acosh(',
    '__HYPERBOLIC_SECANT__': 'self.SECH(',
    '__HYPERBOLIC_ARC_SECANT__': 'self.arcsech(',
    '__HYPERBOLIC_A_SECANT__': 'self.asech(',
    '__HYPERBOLIC_TANGENT__': 'self.TANH(',
    '__HYPERBOLIC_ARC_TANGENT__': 'self.arctanh(',
    '__HYPERBOLIC_A_TANGENT__': 'self.atanh(',
    '__HYPERBOLIC_COTANGENT__': 'self.COTH(',
    '__HYPERBOLIC_ARC_COTANGENT__': 'self.arccoth(',
    '__HYPERBOLIC_A_COTANGENT__': 'self.acoth(',
}

_IN_EXPRESSION_OPERATION  = {
    '__ADD__': '+',
    '__SUBTRACT__': '-',
    '__DIVIDE__': '/',
    '__MULTIPLY__': '*',
    '__POWER__': '**',
    '__LEFT_PARENTHESIS__': '(',
    '__RIGHT_PARENTHESIS__': ')',
    '__NATURAL_LOGARITHM__': 'ln',
    '__SEZIMAL_LOGARITHM__': 'lsez',
    '__DECIMAL_LOGARITHM__': 'ldec',
    '__SQUARE__': '\u200b²',
    '__SQUARE_ROOT__': 'sqrt',
    '__CUBE__': '\u200b³',
    '__CUBIC_ROOT__': 'cbrt',
    '__MODULO__': ' mod ',
    '__FACTORIAL__': '!',
    '__SINE__': 'SIN(',
    '__ARC_SINE__': 'arcsin(',
    '__A_SINE__': 'asin(',
    '__COSECANT__': 'CSC(',
    '__ARC_COSECANT__': 'arccsc(',
    '__A_COSECANT__': 'acsc(',
    '__COSINE__': 'COS(',
    '__ARC_COSINE__': 'arccos(',
    '__A_COSINE__': 'acos(',
    '__SECANT__': 'SEC(',
    '__ARC_SECANT__': 'arcsec(',
    '__A_SECANT__': 'asec(',
    '__TANGENT__': 'TAN(',
    '__ARC_TANGENT__': 'arctan(',
    '__A_TANGENT__': 'atan(',
    '__COTANGENT__': 'COT(',
    '__ARC_COTANGENT__': 'arccot(',
    '__A_COTANGENT__': 'acot(',
    '__HYPERBOLIC_SINE__': 'SINH(',
    '__HYPERBOLIC_ARC_SINE__': 'arcsinh(',
    '__HYPERBOLIC_A_SINE__': 'asinh(',
    '__HYPERBOLIC_COSECANT__': 'CSCH(',
    '__HYPERBOLIC_ARC_COSECANT__': 'arccsch(',
    '__HYPERBOLIC_A_COSECANT__': 'acsch(',
    '__HYPERBOLIC_COSINE__': 'COSH(',
    '__HYPERBOLIC_ARC_COSINE__': 'arccosh(',
    '__HYPERBOLIC_A_COSINE__': 'acosh(',
    '__HYPERBOLIC_SECANT__': 'SECH(',
    '__HYPERBOLIC_ARC_SECANT__': 'arcsech(',
    '__HYPERBOLIC_A_SECANT__': 'asech(',
    '__HYPERBOLIC_TANGENT__': 'TANH(',
    '__HYPERBOLIC_ARC_TANGENT__': 'arctanh(',
    '__HYPERBOLIC_A_TANGENT__': 'atanh(',
    '__HYPERBOLIC_COTANGENT__': 'COTH(',
    '__HYPERBOLIC_ARC_COTANGENT__': 'arccoth(',
    '__HYPERBOLIC_A_COTANGENT__': 'acoth(',
}

_NICE_OPERATION = {
    '__ADD__': ' + ',
    '__SUBTRACT__': ' − ',
    '__DIVIDE__': ' ÷ ',
    '__MULTIPLY__': ' × ',
    '__POWER__': ' ^ ',
    '__PERCENT__': '%',
    '__PERMILLE__': '‰',
    '__PERMYRIAD__': '‱',
    '__PERSIX__': '󱹰',
    '__PERNIF__': '󱹱',
    '__PERARDA__': '󱹲',
    '__PERSIXARDA__': '󱹳',
    '__PERNIFARDA__': '󱹴',
    '__PERSHADARA__': '󱹵',
    '__PERSIXSHADARA__': '󱹶',
    '__PERNIFSHADARA__': '󱹷',
    '__PERARDASHADARA__': '󱹸',
    '__PERSIXARDASHADARA__': '󱹹',
    '__PERNIFARDASHADARA__': '󱹺',
    '__PERDISHADARA__': '󱹻',
    '__PERTRISHADARA__': '󱹼',
    '__PERCHARSHADARA__': '󱹽',
    '__PERPANSHADARA__': '󱹾',
    '__PERSHASHADARA__': '󱹿',
    '__LEFT_PARENTHESIS__': '(',
    '__RIGHT_PARENTHESIS__': ')',
    '__NATURAL_LOGARITHM__': 'ln',
    '__SEZIMAL_LOGARITHM__': 'lsez',
    '__DECIMAL_LOGARITHM__': 'ldec',
    '__SQUARE__': '\u200b²',
    '__SQUARE_ROOT__': 'sqrt',
    '__CUBE__': '\u200b³',
    '__CUBIC_ROOT__': 'cbrt',
    '__MODULO__': ' mod ',
    '__FACTORIAL__': '!',
    '__SINE__': 'sin(',
    '__ARC_SINE__': 'arcsin(',
    '__A_SINE__': 'asin(',
    '__COSECANT__': 'csc(',
    '__ARC_COSECANT__': 'arccsc(',
    '__A_COSECANT__': 'acsc(',
    '__COSINE__': 'cos(',
    '__ARC_COSINE__': 'arccos(',
    '__A_COSINE__': 'acos(',
    '__SECANT__': 'sec(',
    '__ARC_SECANT__': 'arcsec(',
    '__A_SECANT__': 'asec(',
    '__TANGENT__': 'tan(',
    '__ARC_TANGENT__': 'arctan(',
    '__A_TANGENT__': 'atan(',
    '__COTANGENT__': 'cot(',
    '__ARC_COTANGENT__': 'arccot(',
    '__A_COTANGENT__': 'acot(',
    '__HYPERBOLIC_SINE__': 'sinh(',
    '__HYPERBOLIC_ARC_SINE__': 'arcsinh(',
    '__HYPERBOLIC_A_SINE__': 'asinh(',
    '__HYPERBOLIC_COSECANT__': 'csch(',
    '__HYPERBOLIC_ARC_COSECANT__': 'arccsch(',
    '__HYPERBOLIC_A_COSECANT__': 'acsch(',
    '__HYPERBOLIC_COSINE__': 'cosh(',
    '__HYPERBOLIC_ARC_COSINE__': 'arccosh(',
    '__HYPERBOLIC_A_COSINE__': 'acosh(',
    '__HYPERBOLIC_SECANT__': 'sech(',
    '__HYPERBOLIC_ARC_SECANT__': 'arcsech(',
    '__HYPERBOLIC_A_SECANT__': 'asech(',
    '__HYPERBOLIC_TANGENT__': 'tanh(',
    '__HYPERBOLIC_ARC_TANGENT__': 'arctanh(',
    '__HYPERBOLIC_A_TANGENT__': 'atanh(',
    '__HYPERBOLIC_COTANGENT__': 'coth(',
    '__HYPERBOLIC_ARC_COTANGENT__': 'arccoth(',
    '__HYPERBOLIC_A_COTANGENT__': 'acoth(',
}

_PER_OPERATIONS = ('__PERCENT__', '__PERMILLE__', '__PERMYRIAD__', '__PERSIX__', '__PERNIF__', '__PERARDA__', '__PERSIXARDA__', '__PERNIFARDA__', '__PERSHADARA__', '__PERSIXSHADARA__', '__PERNIFSHADARA__', '__PERARDASHADARA__', '__PERSIXARDASHADARA__', '__PERNIFARDASHADARA__', '__PERDISHADARA__', '__PERTRISHADARA__', '__PERCHARSHADARA__', '__PERPANSHADARA__', '__PERSHASHADARA__')

_PER_OPERATIONS_DECIMAL_TO_SEZIMAL = (
    ('%', ' / 244', ' ÷ 24̄', ' ÷ 󱸂󱸜'),
    ('‰', ' / 4_344', ' ÷ 3̄4̄', ' ÷ 󱸛󱸜'),
    ('‱', ' / 114_144', ' ÷ 1̇1̄4̄', ' ÷ 󱸇󱸙󱸜'),
)

_PER_OPERATIONS_SEZIMAL_TO_DECIMAL = (
    ('%', ' / 36'),
    ('‰', ' / 216'),
    ('‱', ' / 1_296'),
    ('󱹰', ' / 6'),
    ('󱹱', ' / 36'),
    ('󱹲', ' / 216'),
    ('󱹳', ' / 1_296'),
    ('󱹴', ' / 7_776'),
    ('󱹵', ' / 46_656'),
    ('󱹶', ' / 279_936'),
    ('󱹷', ' / 1_679_616'),
    ('󱹸', ' / 10_077_696'),
    ('󱹹', ' / 60_466_176'),
    ('󱹺', ' / 362_797_056'),
    ('󱹻', ' / 2_176_782_336'),
    ('󱹼', ' / 101_559_956_668_416'),
    ('󱹽', ' / 4_738_381_338_321_616_896'),
    ('󱹾', ' / 221_073_919_720_733_357_899_776'),
    ('󱹿', ' / 10_314_424_798_490_535_546_171_949_056'),
)

_NO_SPACE_OPERATIONS = (
    '__LEFT_PARENTHESIS__',
    '__RIGHT_PARENTHESIS__',
    '__NATURAL_LOGARITHM__',
    '__SEZIMAL_LOGARITHM__',
    '__DECIMAL_LOGARITHM__',
    '__SQUARE__',
    '__SQUARE_ROOT__',
    '__CUBE__',
    '__CUBIC_ROOT__',
    '__FACTORIAL__',
    '__SINE__',
    '__ARC_SINE__',
    '__A_SINE__',
    '__COSECANT__',
    '__ARC_COSECANT__',
    '__A_COSECANT__',
    '__COSINE__',
    '__ARC_COSINE__',
    '__A_COSINE__',
    '__SECANT__',
    '__ARC_SECANT__',
    '__A_SECANT__',
    '__TANGENT__',
    '__ARC_TANGENT__',
    '__A_TANGENT__',
    '__COTANGENT__',
    '__ARC_COTANGENT__',
    '__A_COTANGENT__',
)

_TRIGONOMETRIC_FUNCTION = (
    '__SINE__',
    '__ARC_SINE__',
    '__A_SINE__',
    '__COSECANT__',
    '__ARC_COSECANT__',
    '__A_COSECANT__',
    '__COSINE__',
    '__ARC_COSINE__',
    '__A_COSINE__',
    '__SECANT__',
    '__ARC_SECANT__',
    '__A_SECANT__',
    '__TANGENT__',
    '__ARC_TANGENT__',
    '__A_TANGENT__',
    '__COTANGENT__',
    '__ARC_COTANGENT__',
    '__A_COTANGENT__',
)


_CONSTANTS = ('e', 'π', 'τ', 'φ')

e = E
π = PI
τ = TAU
φ = GOLDEN_RATIO

